---
title: "& č. 39; Ukončit zkuste & č. 39; může být použit pouze uvnitř a & č. 39; Zkuste & č. 39; příkaz"
ms.date: 07/20/2015
ms.prod: .net
ms.technology:
- devlang-visual-basic
ms.topic: article
f1_keywords:
- vbc30393
- bc30393
helpviewer_keywords:
- BC30393
ms.assetid: b8651df3-a32f-478c-a6d8-aa0ef584155f
caps.latest.revision: 
author: dotnet-bot
ms.author: dotnetcontent
ms.openlocfilehash: 7eed9e67e08c131a02ff1439c7ac37b1d67049ca
ms.sourcegitcommit: 34ec7753acf76f90a0fa845235ef06663dc9e36e
ms.translationtype: MT
ms.contentlocale: cs-CZ
ms.lasthandoff: 12/21/2017
---
# <a name="39exit-try39-can-only-appear-inside-a-39try39-statement"></a>& č. 39; Ukončit zkuste & č. 39; může být použit pouze uvnitř a & č. 39; Zkuste & č. 39; příkaz
`Exit Try`lze použít pouze v rámci `Try` blokovat příkaz. Máte buď redundantní `Exit Try` prohlášení, nebo vaše `Exit Try` příkaz zobrazí mimo hranice jeho odpovídající `Try` bloku.  
  
 **ID chyby:** BC30393  
  
## <a name="to-correct-this-error"></a>Oprava této chyby  
  
1.  Vyhledejte a odeberte nadbytečné `Exit Try` příkaz.  
  
2.  Přesunout `Exit Try` příkaz na příslušné místo vašeho kódu.  
  
## <a name="see-also"></a>Viz také  
 [Příkaz Try...Catch...Finally](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)  
 
